# Generated by Django 4.0.8 on 2025-08-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_courseallocation_session'),
        ('core', '0004_googlemeetlink_remove_semester_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='googlemeetlink',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
