# Generated by Django 4.0.8 on 2025-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.AddField(
            model_name='program',
            name='program_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='program_id_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_id_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_id_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_id_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
