# Generated by Django 4.0.8 on 2025-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_credit_remove_course_is_elective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('22Days', 'CPT: 22Days'), ('44Days', 'CPTE: 44Days')], max_length=25),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.TextField(default='00000'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id_en',
            field=models.TextField(default='00000', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id_es',
            field=models.TextField(default='00000', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id_fr',
            field=models.TextField(default='00000', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id_ru',
            field=models.TextField(default='00000', null=True),
        ),
    ]
