# Generated by Django 4.0.8 on 2025-08-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_googlemeetlink_remove_semester_session'),
        ('course', '0006_alter_course_level_alter_program_program_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.googlemeetlink'),
        ),
    ]
