# Generated by Django 5.2.4 on 2025-07-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_admin'),
    ]

    operations = [
        # This migration is a placeholder since the field renaming was done via code changes
        # The fields were already renamed in the model and throughout the codebase
    ]
