# Generated by Django 4.0.8 on 2025-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_role_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_parent',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('22Days', '22Days'), ('44Days', '44Days')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
