# Generated by Django 4.0.8 on 2025-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_parent_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('22Days', 'CPT: 22Days'), ('44Days', 'CPTE: 44Days')], max_length=25, null=True),
        ),
    ]
