# Generated by Django 4.0.8 on 2025-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('CPT: 22Days', 'CPT: 22Days'), ('CPTE: 44Days', 'CPTE: 44Days')], max_length=25, null=True),
        ),
    ]
