# Generated by Django 4.0.8 on 2025-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_id_number_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('CPT: 22Days', 'CPT(22Days)'), ('CPTE: 44Days', 'CPTE(44Days)')], max_length=25, null=True),
        ),
    ]
